"""add entrada,saida tables

Revision ID: 7e05a2532b1e
Revises: 
Create Date: 2023-08-23 14:20:49.900743

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7e05a2532b1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Crie as tabelas
    op.create_table(
        'entradas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('descricao', sa.String(), nullable=True),
        sa.Column('valor', sa.Float(), nullable=True),
        sa.Column('date', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'saidas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('descricao', sa.String(), nullable=True),
        sa.Column('valor', sa.Float(), nullable=True),
        sa.Column('date', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
