version: '3.11'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - app-volume:/app
    command: sh -c "uvicorn app:app --host 0.0.0.0 --reload"

  

volumes:
  app-volume: